# List of chemical and cell lines included in the analysis.
cell_line: 
 - "COV434" 
 - "KGN"
 - "Primary"
chemical: 
 - "DES"
 - "KTZ"

# List of constrast
contrast:
 - "DES_10-10M"
 - "DES_10-6M"
 - "KTZ_10-9M"
 - "KTZ_10-5M"

# List of groups
group: 
 - "DES6"
 - "DES10"
 - "KTZ5"
 - "KTZ9"
