channels:
- conda-forge
- bioconda
- r
dependencies:
- snakemake-minimal
- r-msigdbr
- bioconductor-org.Hs.eg.db
- bioconductor-deseq2=1.30.1
- bioconductor-clusterProfiler
- bioconductor-biomaRt
- bioconductor-pathview
- r-umap
- r-RColorBrewer
- r-dplyr
- bioconductor-DOSE
- r-venndiagram
- r-ggplot2
- r-BiocManager
- python
- r-argparse
- rstudio
- r-rmarkdown
- r-pheatmap


