channels:
- bioconda
- conda-forge
- defaults
dependencies:
- r-msigdbr=7.4.1
- bioconductor-org.Hs.eg.db=3.12.0
- bioconductor-deseq2=1.30.1
- bioconductor-clusterProfiler=3.18.1
- bioconductor-pathview=1.30.1
- bioconductor-dose=3.16.0
- bioconductor-do.db=2.9
- bioconductor-ggtree=2.4.1
- r-rvcheck=0.1.8
- r-base=4.0.5
- bioconductor-biomaRt=2.46.3
- r-umap=0.2.7.0
- r-RColorBrewer=1.1_2
- r-dplyr=1.0.7
- r-ggplot2=3.3.5
- r-BiocManager=1.30.16
- python=3.10.1
- r-rmarkdown=2.11
- r-pheatmap=1.0.12
- bioconductor-apeglm=1.12.0 
- r-tidyverse=1.3.1
- rstudio=1.1.456
- bioconductor-tximport=1.18.0
- r-readr=2.1.1
- bioconductor-ensdb.hsapiens.v86=2.99.0
- bioconductor-ensembldb=2.14.0
- bioconductor-edger=3.32.1
- bioconductor-limma=3.46.0
- r-patchwork=1.1.1
- r-seurat=4.0.6
- r-cowplot=1.1.1
- r-clustree=0.4.4
- r-venndiagram=1.7.1 
- r-ggraph=2.0.5
- bioconductor-singlecellexperiment=1.12.0
- r-matrix.utils=0.9.8
- r-Matrix=1.4_0
- bioconductor-slingshot=1.8.0
- bioconductor-singler=1.4.1
- r-swamp=1.5.1
- r-openxlsx=4.2.5
- bioconductor-gsva=1.38.2
- bioconductor-gseabase=1.52.1



