channels:
- bioconda
- conda-forge
- defaults
dependencies:
- r-msigdbr
- bioconductor-org.Hs.eg.db
- bioconductor-deseq2
- bioconductor-clusterProfiler
- bioconductor-pathview
- bioconductor-dose
- bioconductor-do.db
- bioconductor-ggtree
- r-rvcheck=0.1.8
- r-base=4.0.5
- bioconductor-biomaRt
- r-umap
- r-RColorBrewer
- r-dplyr
- r-ggplot2
- r-BiocManager
- python
- r-rmarkdown
- r-pheatmap
- bioconductor-apeglm 
- r-tidyverse
- rstudio
- bioconductor-tximport
- r-readr
- bioconductor-ensdb.hsapiens.v86
- bioconductor-ensembldb
- bioconductor-edger
- bioconductor-limma
- r-patchwork
- r-seurat
- r-cowplot
- r-clustree
- r-venndiagram 
- r-ggraph
- bioconductor-singlecellexperiment
- r-matrix.utils
- r-Matrix
- bioconductor-slingshot
- bioconductor-singler
- bioconductor-ggtree 
- r-swamp
- r-openxlsx
- bioconductor-gsva
- bioconductor-gseabase



