channels:
- conda-forge
- bioconda
- r
- defaults
dependencies:
- r-msigdbr
- bioconductor-org.Hs.eg.db
- bioconductor-deseq2=1.30.1
- bioconductor-clusterProfiler
- bioconductor-biomaRt
- bioconductor-pathview
- r-umap
- r-RColorBrewer
- r-dplyr
- bioconductor-DOSE
- r-venndiagram
- r-ggplot2
- r-BiocManager
- python
- r-argparse
- r-rmarkdown
- r-pheatmap
- r-base=4.0.5
- r-digest
- bioconductor-apeglm 
- r-tidyverse
- rstudio
- bioconductor-tximport
- r-readr
- bioconductor-ensdb.hsapiens.v86
- bioconductor-ensembldb
- bioconductor-s4vectors
- bioconductor-edger 

