---
title: "DE analysis"
author: "Tianyi"
date: "4/23/2021"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
params:
    counts_matrix: "/data/subreadCounts.txt"
    sample_info: "/data/info.csv"
    cell_line: "COV434 KGN Primary"
    chemical: "DES KTZ" 
---

```{r setup, include=FALSE}
.libPaths("/Users/tili/miniconda3/envs/Cell_bulk_202011/lib/R/library")
knitr::opts_chunk$set(echo = TRUE)
```

# Cell line bulk RNAseq analysis - DES and KTZ samples

DE analysis.  

## Load required library

```{r Load dependencies}
library(dplyr)
library(DESeq2)
library(ggplot2)
library(biomaRt)
```

## Data input

```{r data input}
cells <- read.delim(file = "/Users/tili/Desktop/try/data/DES.txt")
info <- read.csv(file = "/Users/tili/Desktop/try/data/info.csv", header = T, sep = ";")
cells[is.na(cells)] <- 0 
cell_line <- unlist(strsplit(params$cell_line, " "))
chemical <- unlist(strsplit(params$chemical, " "))
```

## Construct dds object

```{r construct dds object}
dds <- DESeqDataSetFromMatrix(countData=cells_ordered, colData = info, design = ~ group) 
```

## Set refernece group

```{r set reference group}
dds$group <- relevel(dds$group, ref = "DMSO")
```

## DE analysis 

```{r DE analysis}
dds <-DESeq(dds)

res <- results(dds, contrast = c("group", "DES_10-10M", "DMSO"), independentFiltering = T, pAdjustMethod = "fdr")
res <- results(dds, contrast = c("group", "DES_10-6M", "DMSO"), independentFiltering = T, pAdjustMethod = "fdr")
res.sig <- as.data.frame(res.sig)
res.sig <- res[which(res$padj<0.05),]
res.sig <- res.sig[order(res.sig$padj),]
summary(res.sig)
```

## Plot MA plot

```{r MA plot}
plotMA(res)
```

## Shrunk results for downstream functional analysis

```{r shrunk results}
contrast <- c("group", "DES_10-10M", "DMSO") 
# for the functional analysis such as GO analysis, shrinkage of the fold changes is recommended
res_shrunk <- results(dds, contrast = contrast, alpha = 0.05)
res_shrunk <- lfcShrink(dds, coef = 2, type = "apeglm", lfcThreshold = 1)

res.sig.shrunk <- data.frame(res_shrunk)
res.sig.shrunk <- res_shrunk[which(res_shrunk$svalue<0.05),]
res.sig.shrunk <- res.sig.shrunk[order(res.sig.shrunk$svalue),]
summary(res.sig.shrunk)
```

## get gene names from gene id

```{r get gene names}
mart <- useEnsembl(biomart = "ensembl",dataset = "hsapiens_gene_ensembl")
output <- getBM(attributes=c("ensembl_gene_id","external_gene_name","entrezgene_id","description"), mart = mart)
res.sig <- as.data.frame(res.sig)
res.sig$geneID <- rownames(res.sig)
final <- merge(res.sig, output, by.x = "geneID", by.y = "ensembl_gene_id", all.x = T, all.y = F)

output <- getBM(attributes=c("ensembl_gene_id","external_gene_name","entrezgene_id","description"), mart = mart)
res.sig.shrunk <- as.data.frame(res.sig.shrunk)
res.sig.shrunk$geneID <- rownames(res.sig.shrunk)
final_shrunk <- merge(res.sig.shrunk, output, by.x = "geneID", by.y = "ensembl_gene_id", all.x = T, all.y = F)
```

# Get background gene sets

```{r get background genes for functional analysis}
all_genes <- data.frame(res_shrunk)

output <- getBM(attributes=c("ensembl_gene_id","external_gene_name","entrezgene_id","description"), mart = mart)
all_genes$geneID <- rownames(all_genes)
all <- merge(all_genes, output, by.x = "geneID", by.y = "ensembl_gene_id", all.x = T, all.y = F)
```

# Get log2FC and entrezgene id for functional analysis

```{r get background genes for functional analysis}
genelist <- all %>% 
  dplyr::select(entrezgene_id, log2FoldChange) 

List <- genelist$log2FoldChange
names(List) <- as.character(genelist$entrezgene_id)
List <- sort(List, decreasing = T)
```

## Save the output data

```{r save output}
write.csv(final, file = "/Users/tili/Desktop/try/results/sig_0_05_DE_genes.csv")
write.csv(final_shrunk, file = "/Users/tili/Desktop/try/results/sig_0_05_DE_genes_shrunk.csv")
write.csv(all, file = "/Users/tili/Desktop/try/results/background_genes_shrunk.csv")
write.csv(List, file = "/Users/tili/Desktop/try/results/background_genes_list_log2fc_shrunk.csv")
```

```{r Session info}
sessionInfo()
```
