---
title: "Nuclear receptor expression in DES and KTZ samples"
date: "'r format(Sys.time(), '%d %B%, %Y')'"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
params:
    counts_matrix: "/Users/tili/Desktop/Results/PCR/bulk seq_primary_KGN_COV/DESeq2/subreadCounts.txt"
    sample_info: "/Users/tili/Desktop/Results/PCR/bulk seq_primary_KGN_COV/DESeq2/forskolin info.csv"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

# Cell line bulk RNAseq analysis - Nuclear receptor expression in DES and KTZ samples

## R Markdown

### subsection


```{r dependencies, include = T}
library(dplyr)
library(DESeq2)
library(pheatmap)
library(umap)
library(biomaRt)
library(org.Hs.eg.db)
library(pathview)
library(clusterProfiler)
library(msigdbr)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, fig.width = 6, fig.height = 4}
plot(get(params$data), col = params$color)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r pressure 2, echo = FALSE, fig.width = 9, out.width = "560px"}
plot(pressure)
```

```{r}
library(networkD3)
data(MisLinks, MisNodes)
forceNetwork(Links = MisLinks, Nodes = MisNodes, Source = "source",
             Target = "target", Value = "value", NodeID = "name",
             Group = "group", opacity = 0.4)
```
